### PR TITLE
Modernize RPM spec file templates

### PR DESCRIPTION
**Pull request by cottsay**
Each commit message contains justification for the change.

### CODE REVIEW

**Comment by cottsay** [comment]
@richmattes, would you mind taking a look at these changes? We'll use very similar templates for the ROS 2 packages for RHEL and Fedora (though this review includes only updates to the ROS 1 templates).

**Comment by richmattes** [comment]
Sure. I'm busy this week but I'll take a look this weekend.

**Comment by richmattes** [comment]
I took a look at the changes, they all look reasonable to me.

**Comment by cottsay** [comment]
Thanks for taking a look, @richmattes and @nuclearsandwich. I'm going to clean up the line breaks in the commit messages and merge this since it won't conflict with the ongoing generator refactor.

**Pull request merged**
