### PR TITLE
Support 'working tree clean' output from git

### PR DESCRIPTION
**Pull request by rohbotics**
This makes bloom work for me on git 2.9.3

Connects to #398

### CODE REVIEW

**Comment by wjwwood** [comment]
Thanks for looking into @rohbotics!

**Comment by davetcoleman** [comment]
Can you release this now? I'm on Kinetic shadow-fixed but still having this issue.

**Comment by davetcoleman** [comment]
Note it works from source, as [documented](https://github.com/ros-infrastructure/bloom/pull/405)

**Comment by wjwwood** [comment]
Python package are not usually different between public and shadow fixed. I cannot release it now, but I will as soon as I have time.

**Comment by paulbovbel** [comment]
Could you please cut a release with this fix?

**Comment by wjwwood** [comment]
I just released `0.5.23`, sorry for the wait.

**Pull request merged**
