### PR TITLE
use the distribution type instead of hard coded lists

### PR DESCRIPTION
**Pull request by dirk-thomas**
Related to #496.

The first three commits only move existing code from the `command/release` module into the `github` and ~~rosdistro~~ `rosdistro_api` modules.

The fourth commit actually changes behavior / logic and uses the ROS distro names with a type `ros2` instead of hard coded lists.

### CODE REVIEW

**Comment by dirk-thomas** [comment]
After fixing the poor choice of naming the new module `rosdistro` and renaming it to `rosdistro_api` (and rebasing for better review / history) this should be ready for review.

**Comment by tfoote** [comment]
browsing the file added in 13e895eda07f12e3d3adfd17d5ed63b756ebccae it doesn't appear to have any history tracked

**Comment by nuclearsandwich** [comment]
Merged this locally to see if I could squeeze it into today's release. Creating a test release in an empty release repo yielded a stacktrace on python2 and python3.  I haven't investigated beyond this report.

```
❯ bloom-release -r crystal ament_cmake --override-release-repository-url git@github.com:nuclearsandwich/ament_cmake-release
Traceback (most recent call last):
  File "/home/steven/osrf/venv.bloom/bin/bloom-release", line 11, in <module>
    load_entry_point('bloom', 'console_scripts', 'bloom-release')()
  File "/home/steven/osrf/bloom/bloom/commands/release.py", line 1194, in main
    args.override_release_repository_push_url)
  File "/home/steven/osrf/bloom/bloom/commands/release.py", line 1038, in perform_release
    release_repo = get_release_repo(repository, distro, override_release_repository_url)
  File "/home/steven/osrf/bloom/bloom/commands/release.py", line 287, in get_release_repo
    url = get_repo_uri(repository, distro)
  File "/home/steven/osrf/bloom/bloom/commands/release.py", line 233, in get_repo_uri
    distribution_file = get_distribution_file(distro)
  File "/home/steven/osrf/bloom/bloom/commands/release.py", line 159, in get_distribution_file
    if distro not in _rosdistro_distribution_files:
NameError: name '_rosdistro_distribution_files' is not defined
```

**Comment by nuclearsandwich** [comment]
> The changes in [30b1631](https://github.com/ros-infrastructure/bloom/commit/30b16310b01f2fff15f471babf07fe864c6a84d3) look good. The copy doesn't seem to have tracked history though.

I can get history locally with `git log --follow bloom/rosdistro_api.py`

**Comment by dirk-thomas** [comment]
> Creating a test release in an empty release repo yielded a stacktrace ...

The `get_distribution_file` function in the `release` module was a left over. I updated the code to remove it and import the function from the new `rosdistro_api` module.

**Pull request merged**
