### PR TITLE
Evaluate dependency conditions

### PR DESCRIPTION
**Pull request by nuclearsandwich**
Noodling on this approach in order to try and unblock @AAlon.

Quite aside from the clear need to factor the condition check into a function, a few other things stand out as worth considering before merging:
* For consistent results, maybe we could get our context from the bloom tracks.yaml rather than the environment
* I used comprehensions to filter conditions on lists of dependencies roughly in place but it's worth looking more closely (at a better time of day) to see if there's any reason not to check the evaluated conditions lazily after the list of keys to evaluate is generated rather than doing it on each list as its constructed.

An additional TODO is to check that the build_type condition is also checked and honored.

### CODE REVIEW

**Comment by nuclearsandwich** [comment]
I put this in ready because I was curious where the Travis-CI output was. It seems this draft-state PR biz interferes with Travis running.

**Comment by nuclearsandwich** [comment]
@AAlon I tweaked this so it gets the conditonal context from the rosdistro index rather than the local environment as I think that's a more reasonable primary source. Details in 0cdcd09.

It behaved sensibly for my canary package but I'm sure it could do with more rigorous field testing.

**Comment by AAlon** [comment]
Thanks a lot for the quick fix! we'll retry the release in the next couple of days and will let you know how it goes.

**Comment by nuclearsandwich** [comment]
The CI failure is due to my rpm implementation apparently being incomplete. I'll be able to address it before the fix is released.

**Comment by AAlon** [comment]
> The CI failure is due to my rpm implementation apparently being incomplete. I'll be able to address it before the fix is released.

The RPM issue was blocking from actually going forward with the release as the tracks update stage is performed after RPM generation. The changes don't look specific to debian/rpm so I went ahead and copied the same changes you've made in `debian/generator.py` to `rpm/generator.py` (might be better to extract it into `common.py`...). Seems like it's working :-)
kinetic: https://github.com/ros/rosdistro/pull/20614
melodic: https://github.com/ros/rosdistro/pull/20615

**Comment by JWhitleyAStuff** [comment]
Tested on hybrid package `ml_classifiers`. Seems to work correctly with changes suggested by @AAlon:

Kinetic: https://github.com/ros/rosdistro/pull/20839
Melodic: https://github.com/ros/rosdistro/pull/20840
Crystal: https://github.com/ros/rosdistro/pull/20841

PR for changes suggested by @AAlon: #527

**Comment by nuclearsandwich** [comment]
@cottsay if you have time to review the changes tomorrow (hopefully today before you read this) then that's great. If not, no worries as I'm pretty certain that this won't break existing distros supporting Fedora. It should bring full conditional dependency support to Fedora but testing the ROS 2 side fails since the ament build types aren't yet supported.

**Comment by nuclearsandwich** [comment]
> `ROS_PYTHON_VERSION`

I haven't added this yet because I'm not sure where we ought to get it from. We set the ROS_VERSION for bloomed packages from the distribution type but we have no such info for the python version. I could see it being added either to the index or to the distribution.yaml files as part of the platform metadata but I've been hesitant to pull from the local environment.

**Pull request merged**
