### PR TITLE
Travis CI: Add Python 3.7 to the testing

### PR DESCRIPTION
**Pull request by cclauss**
Add Python 3.7 to the testing in alignment with travis-ci/travis-ci#9069

### CODE REVIEW

**Comment by cclauss** [comment]
__async__ and __os.errno__ are two examples that I have been running into but https://docs.python.org/3/whatsnew/3.7.html has others.  I am OK if you do not want to add complexity to the testing.

**Comment by wjwwood** [comment]
@cclauss well, since we're not using `asyncio` then I'd say we don't really need it. I wasn't aware of `os.errno` changing, but I don't think we're using that either.

I think I would decline this until either the 3.7 workaround is no longer required (`sudo: true` make it slower) or we're actively using some feature that's changed in 3.7. Also, none of our ubuntu or debian platforms use 3.7 yet, though I recognize others are using it already (I'm using it on my mac).

**Comment by cclauss** [comment]
Understood.  FYI, I have not seen the slowness of sudo on Travis.  The 3.7 job usually start first and complete in less time than the Docker jobs.

**Comment by wjwwood** [comment]
That may have changed at some point, but for a long time they were discouraging the use of the `sudo: true` option. I still would prefer to reevaluate this when the 3.7 issues have been resolved upstream (if that ever happens).

**Pull request closed without merging**
