### PR TITLE
fix bad handling of conflicts/replaces

### PR DESCRIPTION
**Pull request by vrabaud**
that patch works for me for naoqi_bridge

I don't understand why the package variable is even used, it's part of the previous loop.

### CODE REVIEW

**Comment by vrabaud** [comment]
btw, I cannot release naoqi_bridge otherwise (it says one of the packages depends on a package it actually only conflicts with)

**Comment by vrabaud** [comment]
it seems Travis is failing for lines I did not change.

**Comment by wjwwood** [comment]
Looks like the `pep8` module got an update, I'll fix those.

**Comment by wjwwood** [comment]
I opened https://github.com/ros-infrastructure/bloom/pull/361

Once that is merged you'll need to rebase this.

**Comment by wjwwood** [comment]
Ok, it's merged.

**Comment by wjwwood** [comment]
I rebased, tested, and merged locally.

**Comment by vrabaud** [comment]
though this bug is bad, it only affects naoqi* it seems so I can wait, I patched my bloom version :)

**Comment by wjwwood** [comment]
Ok, great. Thanks for fixing it.

**Pull request merged**
