### PR TITLE
add options to override release repo urls

### PR DESCRIPTION
**Pull request by wjwwood**

### CODE REVIEW

**Comment by mikepurvis** [comment]
LGTM

**Comment by piyushk** [comment]
This PR looks like a great addition. I've found a minor issue. The release repo url is not overridden in the pull request (see https://github.com/ros/rosdistro/pull/7035). Here's the relevant output:

```
piyushk@robot-devil:~/source/libfreenect$ bloom-release --rosdistro indigo --track indigo libfreenect --edit --override-release-repository-url https://github.com/ros-drivers-gbp/libfreenect-ros-release.git
ROS Distro index file associate with commit 'd171ec5484941f20cea31da4fc5b55b558911d61'
Overriding the release repository url, using 'https://github.com/ros-drivers-gbp/libfreenect-ros-release.git'
==> Fetching 'libfreenect' repository from 'https://github.com/ros-drivers-gbp/libfreenect-ros-release.git'
Cloning into '/tmp/tmp7ctmC9'...
remote: Counting objects: 3, done.
remote: Compressing objects: 100% (2/2), done.
remote: Total 3 (delta 0), reused 0 (delta 0)
Unpacking objects: 100% (3/3), done.
Creating track 'indigo'...
...
Everything went as expected, you should check that the new tags match your expectations, and then push to the release repo with:
  git push --all && git push --tags  # You might have to add --force to the second command if you are over-writing existing tags
<== Released 'libfreenect' using release track 'indigo' successfully
==> git remote -v
origin	https://github.com/ros-drivers-gbp/libfreenect-ros-release.git (fetch)
origin	https://github.com/ros-drivers-gbp/libfreenect-ros-release.git (push)
Releasing complete, push to release repository?
Continue [Y/n]? y
==> Pushing changes to release repository for 'libfreenect'
==> git push --all
To https://github.com/ros-drivers-gbp/libfreenect-ros-release.git
   ec3c6a9..2b79d89  master -> master
 * [new branch]      debian/indigo/libfreenect -> debian/indigo/libfreenect
 * [new branch]      debian/indigo/saucy/libfreenect -> debian/indigo/saucy/libfreenect
 * [new branch]      debian/indigo/trusty/libfreenect -> debian/indigo/trusty/libfreenect
 * [new branch]      patches/debian/indigo/libfreenect -> patches/debian/indigo/libfreenect
 * [new branch]      patches/debian/indigo/saucy/libfreenect -> patches/debian/indigo/saucy/libfreenect
 * [new branch]      patches/debian/indigo/trusty/libfreenect -> patches/debian/indigo/trusty/libfreenect
 * [new branch]      patches/release/indigo/libfreenect -> patches/release/indigo/libfreenect
 * [new branch]      patches/rpm/indigo/21/libfreenect -> patches/rpm/indigo/21/libfreenect
 * [new branch]      patches/rpm/indigo/heisenbug/libfreenect -> patches/rpm/indigo/heisenbug/libfreenect
 * [new branch]      patches/rpm/indigo/libfreenect -> patches/rpm/indigo/libfreenect
 * [new branch]      release/indigo/libfreenect -> release/indigo/libfreenect
 * [new branch]      rpm/indigo/21/libfreenect -> rpm/indigo/21/libfreenect
 * [new branch]      rpm/indigo/heisenbug/libfreenect -> rpm/indigo/heisenbug/libfreenect
 * [new branch]      rpm/indigo/libfreenect -> rpm/indigo/libfreenect
 * [new branch]      upstream -> upstream
<== Pushed changes successfully
==> Pushing tags to release repository for 'libfreenect'
==> git push --tags
To https://github.com/ros-drivers-gbp/libfreenect-ros-release.git
 * [new tag]         debian/ros-indigo-libfreenect_0.5.1-0_saucy -> debian/ros-indigo-libfreenect_0.5.1-0_saucy
 * [new tag]         debian/ros-indigo-libfreenect_0.5.1-0_trusty -> debian/ros-indigo-libfreenect_0.5.1-0_trusty
 * [new tag]         release/indigo/libfreenect/0.5.1-0 -> release/indigo/libfreenect/0.5.1-0
 * [new tag]         rpm/ros-indigo-libfreenect-0.5.1-0_21 -> rpm/ros-indigo-libfreenect-0.5.1-0_21
 * [new tag]         rpm/ros-indigo-libfreenect-0.5.1-0_heisenbug -> rpm/ros-indigo-libfreenect-0.5.1-0_heisenbug
 * [new tag]         upstream/0.5.1 -> upstream/0.5.1
<== Pushed tags successfully
==> Generating pull request to distro file located at 'https://raw.github.com/ros/rosdistro/master/indigo/distribution.yaml'
Would you like to add documentation information for this repository? [Y/n]? y
==> Looking for a doc entry for this repository in a different distribution...
No existing doc entries found for use as defaults.
Please enter your repository information for the doc generation job.
This information should point to the repository from which documentation should be generated.
VCS Type must be one of git, svn, hg, or bzr.
VCS type: git
VCS url: 
Nothing entered for url.
Try again [Y/n]? n
Would you like to add source information for this repository? [Y/n]? y
==> Looking for a source entry for this repository in a different distribution...
No existing source entries found for use as defaults.
Please enter information which points to the active development branch for this repository.
This information is used to run continuous integration jobs and for developers to checkout from.
VCS Type must be one of git, svn, hg, or bzr.
VCS type: 
'None' is not a valid vcs type.
Try again [Y/n]? n
Unified diff for the ROS distro file located at '/tmp/tmpVXyN43/libfreenect-0.5.1-0.patch':
--- ../indigo/distribution.yaml
+++ ../indigo/distribution.yaml
@@ -3203,7 +3203,7 @@
       tags:
         release: release/indigo/{package}/{version}
       url: https://github.com/ros-drivers-gbp/libfreenect-release.git
-      version: 0.1.2-2
+      version: 0.5.1-0
     status: maintained
   libg2o:
     release:
==> Checking on GitHub for a fork to make the pull request from...
==> Using this fork to make a pull request from: piyushk/rosdistro
==> Cloning piyushk/rosdistro...
==> mkdir -p rosdistro
==> git init
Initialized empty Git repository in /tmp/HrtZgD/rosdistro/.git/
Pull Request Title: libfreenect: 0.5.1-0 in 'indigo/distribution.yaml' [bloom]
Pull Request Body : 
Increasing version of package(s) in repository `libfreenect` to `0.5.1-0`:

- upstream repository: https://github.com/ros-drivers/libfreenect.git
- release repository: https://github.com/ros-drivers-gbp/libfreenect-release.git
- distro file: `indigo/distribution.yaml`
- bloom version: `0.5.16`
- previous version for package: `0.1.2-2`

Open a pull request from 'rosdistro/rosdistro:bloom-libfreenect-0' into 'ros/rosdistro:master'?
Continue [Y/n]? y
==> git checkout -b bloom-libfreenect-0
==> Pulling latest rosdistro branch
remote: Counting objects: 53209, done.
remote: Compressing objects: 100% (20888/20888), done.
remote: Total 53209 (delta 32395), reused 53083 (delta 32300)
Receiving objects: 100% (53209/53209), 12.85 MiB | 5.38 MiB/s, done.
Resolving deltas: 100% (32395/32395), done.
From https://github.com/ros/rosdistro
 * branch            master     -> FETCH_HEAD
==> git reset --hard d171ec5484941f20cea31da4fc5b55b558911d61
HEAD is now at d171ec5 Merge pull request #7034 from carnegieroboticsllc/bloom-multisense_ros-26
==> Writing new distribution file: indigo/distribution.yaml
==> git add indigo/distribution.yaml
==> git commit -m "libfreenect: 0.5.1-0 in 'indigo/distribution.yaml' [bloom]"
[bloom-libfreenect-0 1aed3b9] libfreenect: 0.5.1-0 in 'indigo/distribution.yaml' [bloom]
 1 file changed, 1 insertion(+), 1 deletion(-)
==> Pushing changes to fork
To https://91c489f109b993d0f7f0d20e2e5b9e5bb9c0fa6d:x-oauth-basic@github.com/piyushk/rosdistro.git
 * [new branch]      bloom-libfreenect-0 -> bloom-libfreenect-0
<== Pull request opened at: https://github.com/ros/rosdistro/pull/7035
```

**Comment by piyushk** [comment]
Let me know if I should fix https://github.com/ros/rosdistro/pull/7035 manually, or wait for a fix for this PR and try the --pull-request-only option.

**Comment by wjwwood** [comment]
@piyushk sorry, close that pull request and try again with `--pull-request-only`. The release repo should be fine, the pull request was just wrong.

**Comment by piyushk** [comment]
@wjwwood Thanks! PR ros/rosdistro#7036 looks good.

**Comment by wjwwood** [comment]
Cool, I'll get this into the next bloom release which should be soon.

**Pull request merged**
